In [2]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('marks.csv')

In [5]:
data

name  duration  marks
0  abhi         4     40
1  eric         6     60
2  jack         2     20
3  amit         6     60

In [7]:
y = data['marks']
x = data['duration']

In [8]:
print(y)
print(x)

0    40
1    60
2    20
3    60
Name: marks, dtype: int64
0    4
1    6
2    2
3    6
Name: duration, dtype: int64


In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
mind = LinearRegression()

In [14]:
x

0    4
1    6
2    2
3    6
Name: duration, dtype: int64

In [15]:
x.dtype

dtype('int64')

In [24]:
X = x.values.reshape(4,1)

In [25]:
X

array([[4],
       [6],
       [2],
       [6]])

In [26]:
X.shape

(4, 1)

In [27]:
mind.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
mind.predict([[5]])

array([50.])

In [29]:
mind.predict([[10]])

array([100.])

In [30]:
x

0    4
1    6
2    2
3    6
Name: duration, dtype: int64

In [31]:
x.values

array([4, 6, 2, 6])