In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('marks.csv')

In [3]:
data

name  duration  marks
0  abhi         4     40
1  eric         6     60
2  jack         2     20
3  amit         6     60

In [4]:
type(data)

pandas.core.frame.DataFrame

In [6]:
x = data['duration']
y = data['marks']

In [7]:
x

0    4
1    6
2    2
3    6
Name: duration, dtype: int64

In [8]:
y

0    40
1    60
2    20
3    60
Name: marks, dtype: int64

In [10]:
X = x.values.reshape(4,1)

In [11]:
X

array([[4],
       [6],
       [2],
       [6]])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
mind = LinearRegression()

In [14]:
mind.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
mind.predict([[9]])

array([90.])

In [18]:
# Gives the value of c in y=cx
mind.coef_

array([10.])

In [20]:
# exporting model
from sklearn.externals import joblib

/home/sid/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [22]:
joblib.dump(mind, 'marks_model.pk1')

['marks_model.pk1']