In [2]:
import cv2

In [3]:
photo = cv2.imread('photo.jpg')

In [4]:
photo

array([[[34, 18, 36],
        [34, 18, 36],
        [34, 18, 36],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       [[35, 19, 37],
        [35, 19, 37],
        [35, 19, 37],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       [[36, 20, 38],
        [36, 20, 38],
        [36, 20, 38],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       ...,

       [[37, 17, 12],
        [36, 17, 12],
        [34, 16, 15],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]],

       [[38, 18, 13],
        [38, 18, 13],
        [37, 18, 15],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]],

       [[38, 18, 13],
        [39, 19, 14],
        [38, 19, 14],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]]], dtype=uint8)

In [ ]:
cv2.imshow('hello', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
photo.shape

In [ ]:
import numpy as np

In [8]:
newphoto = cv2.cvtColor(photo, cv2.COLOR_BGR2GRAY)

In [10]:
cv2.imshow('newpic', newphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
newphoto.shape

(288, 552)

In [12]:
newphoto

array([[25, 25, 25, ..., 18, 19, 19],
       [26, 26, 26, ..., 18, 19, 19],
       [27, 27, 27, ..., 18, 19, 19],
       ...,
       [18, 18, 18, ..., 18, 18, 18],
       [19, 19, 19, ..., 18, 18, 18],
       [19, 20, 20, ..., 18, 18, 18]], dtype=uint8)

In [13]:
import numpy as np

In [29]:
c = np.zeros((200,200)) 

In [30]:
c

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
cv2.imshow('c_pic', c)
cv2.waitKey()
cv2.destroyAllWindows()