In [1]:
import cv2

In [2]:
photo = cv2.imread('photo.jpg')

In [3]:
photo

array([[[34, 18, 36],
        [34, 18, 36],
        [34, 18, 36],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       [[35, 19, 37],
        [35, 19, 37],
        [35, 19, 37],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       [[36, 20, 38],
        [36, 20, 38],
        [36, 20, 38],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       ...,

       [[37, 17, 12],
        [36, 17, 12],
        [34, 16, 15],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]],

       [[38, 18, 13],
        [38, 18, 13],
        [37, 18, 15],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]],

       [[38, 18, 13],
        [39, 19, 14],
        [38, 19, 14],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]]], dtype=uint8)

In [4]:
import numpy as np

In [5]:
l = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [6]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [7]:
a = np.array(l)

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [9]:
new_a = a.reshape(4,4)

In [10]:
new_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
new_a[0]

array([1, 2, 3, 4])

In [13]:
new_a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [14]:
photo

array([[[34, 18, 36],
        [34, 18, 36],
        [34, 18, 36],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       [[35, 19, 37],
        [35, 19, 37],
        [35, 19, 37],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       [[36, 20, 38],
        [36, 20, 38],
        [36, 20, 38],
        ...,
        [36, 17, 12],
        [37, 18, 13],
        [37, 18, 13]],

       ...,

       [[37, 17, 12],
        [36, 17, 12],
        [34, 16, 15],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]],

       [[38, 18, 13],
        [38, 18, 13],
        [37, 18, 15],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]],

       [[38, 18, 13],
        [39, 19, 14],
        [38, 19, 14],
        ...,
        [36, 18, 11],
        [36, 18, 11],
        [36, 18, 11]]], dtype=uint8)

In [15]:
cv2.imshow('photo', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
photo.shape

(288, 552, 3)

In [27]:
new_photo = photo[25:100,370:450]

In [28]:
cv2.imshow('cropped photo', new_photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [31]:
photo[0:75,0:80] = new_photo

In [33]:
cv2.imshow('attached_photo', photo)
cv2.waitKey()
cv2.destroyAllWindows()