In [1]:
#split

In [2]:
import cv2 as cv

In [3]:
photo = cv.imread('sample.jpg')

In [5]:
cv.split(photo)

[array([[ 6,  9, 14, ..., 42, 43, 43],
        [11, 12, 16, ..., 39, 39, 40],
        [15, 16, 17, ..., 36, 34, 34],
        ...,
        [54, 53, 53, ..., 70, 67, 64],
        [52, 51, 50, ..., 68, 68, 65],
        [53, 50, 49, ..., 68, 66, 65]], dtype=uint8),
 array([[130, 135, 140, ...,  86,  87,  86],
        [125, 128, 132, ...,  85,  85,  85],
        [120, 123, 125, ...,  84,  84,  83],
        ...,
        [ 91,  90,  90, ...,  88,  85,  82],
        [ 92,  91,  90, ...,  88,  85,  82],
        [ 93,  90,  89, ...,  88,  86,  82]], dtype=uint8),
 array([[184, 190, 198, ...,  87,  88,  89],
        [178, 183, 189, ...,  86,  86,  88],
        [169, 174, 179, ...,  85,  84,  85],
        ...,
        [ 87,  86,  86, ..., 111, 108, 105],
        [ 87,  86,  85, ..., 113, 111, 108],
        [ 88,  85,  84, ..., 113, 111, 108]], dtype=uint8)]

In [6]:
photo

array([[[  6, 130, 184],
        [  9, 135, 190],
        [ 14, 140, 198],
        ...,
        [ 42,  86,  87],
        [ 43,  87,  88],
        [ 43,  86,  89]],

       [[ 11, 125, 178],
        [ 12, 128, 183],
        [ 16, 132, 189],
        ...,
        [ 39,  85,  86],
        [ 39,  85,  86],
        [ 40,  85,  88]],

       [[ 15, 120, 169],
        [ 16, 123, 174],
        [ 17, 125, 179],
        ...,
        [ 36,  84,  85],
        [ 34,  84,  84],
        [ 34,  83,  85]],

       ...,

       [[ 54,  91,  87],
        [ 53,  90,  86],
        [ 53,  90,  86],
        ...,
        [ 70,  88, 111],
        [ 67,  85, 108],
        [ 64,  82, 105]],

       [[ 52,  92,  87],
        [ 51,  91,  86],
        [ 50,  90,  85],
        ...,
        [ 68,  88, 113],
        [ 68,  85, 111],
        [ 65,  82, 108]],

       [[ 53,  93,  88],
        [ 50,  90,  85],
        [ 49,  89,  84],
        ...,
        [ 68,  88, 113],
        [ 66,  86, 111],
        [ 65,  82, 108]]

In [7]:
B,G,R = cv.split(photo)

In [8]:
B

array([[ 6,  9, 14, ..., 42, 43, 43],
       [11, 12, 16, ..., 39, 39, 40],
       [15, 16, 17, ..., 36, 34, 34],
       ...,
       [54, 53, 53, ..., 70, 67, 64],
       [52, 51, 50, ..., 68, 68, 65],
       [53, 50, 49, ..., 68, 66, 65]], dtype=uint8)

In [9]:
# Merging the seperated values in array

In [10]:
cv.merge([B,G,R])

array([[[  6, 130, 184],
        [  9, 135, 190],
        [ 14, 140, 198],
        ...,
        [ 42,  86,  87],
        [ 43,  87,  88],
        [ 43,  86,  89]],

       [[ 11, 125, 178],
        [ 12, 128, 183],
        [ 16, 132, 189],
        ...,
        [ 39,  85,  86],
        [ 39,  85,  86],
        [ 40,  85,  88]],

       [[ 15, 120, 169],
        [ 16, 123, 174],
        [ 17, 125, 179],
        ...,
        [ 36,  84,  85],
        [ 34,  84,  84],
        [ 34,  83,  85]],

       ...,

       [[ 54,  91,  87],
        [ 53,  90,  86],
        [ 53,  90,  86],
        ...,
        [ 70,  88, 111],
        [ 67,  85, 108],
        [ 64,  82, 105]],

       [[ 52,  92,  87],
        [ 51,  91,  86],
        [ 50,  90,  85],
        ...,
        [ 68,  88, 113],
        [ 68,  85, 111],
        [ 65,  82, 108]],

       [[ 53,  93,  88],
        [ 50,  90,  85],
        [ 49,  89,  84],
        ...,
        [ 68,  88, 113],
        [ 66,  86, 111],
        [ 65,  82, 108]]

In [11]:
newphoto = cv.merge([B,G,R])

In [12]:
cv.imshow('Merged_photo', newphoto)
cv.waitKey()
cv.destroyAllWindows()

In [13]:
photo.shape

(768, 1024, 3)

In [15]:
import numpy as np

In [17]:
zero = np.zeros((768,1024))

In [18]:
zero

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
# need to change the data type of Z
Z = zero.astype('uint8')

In [24]:
B.astype

<function ndarray.astype>

In [25]:
B.dtype

dtype('uint8')

In [27]:
new_pic=cv.merge([B,G,Z])

In [28]:
new_pic

array([[[  6, 130,   0],
        [  9, 135,   0],
        [ 14, 140,   0],
        ...,
        [ 42,  86,   0],
        [ 43,  87,   0],
        [ 43,  86,   0]],

       [[ 11, 125,   0],
        [ 12, 128,   0],
        [ 16, 132,   0],
        ...,
        [ 39,  85,   0],
        [ 39,  85,   0],
        [ 40,  85,   0]],

       [[ 15, 120,   0],
        [ 16, 123,   0],
        [ 17, 125,   0],
        ...,
        [ 36,  84,   0],
        [ 34,  84,   0],
        [ 34,  83,   0]],

       ...,

       [[ 54,  91,   0],
        [ 53,  90,   0],
        [ 53,  90,   0],
        ...,
        [ 70,  88,   0],
        [ 67,  85,   0],
        [ 64,  82,   0]],

       [[ 52,  92,   0],
        [ 51,  91,   0],
        [ 50,  90,   0],
        ...,
        [ 68,  88,   0],
        [ 68,  85,   0],
        [ 65,  82,   0]],

       [[ 53,  93,   0],
        [ 50,  90,   0],
        [ 49,  89,   0],
        ...,
        [ 68,  88,   0],
        [ 66,  86,   0],
        [ 65,  82,   0]]

In [29]:
cv.imshow('new_pic', new_pic)
cv.waitKey()
cv.destroyAllWindows()