In [4]:
import tensorflow as tf

In [6]:
a = tf.constant(5)

In [7]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [8]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [9]:
import numpy as np

In [10]:
b = np.array(["hi","feasfeqc","hi"])

In [11]:
type(b)

numpy.ndarray

In [12]:
b

array(['hi', 'feasfeqc', 'hi'], dtype='<U8')

In [13]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [14]:
b = tf.Variable(10)

In [15]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [17]:
b.numpy()

10

In [18]:
b.assign(15)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=15>

In [19]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=15>

In [20]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [21]:
c = a+b

In [22]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [23]:
a = tf.constant(5)
b = tf.constant(6)

In [24]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [25]:
b

<tf.Tensor: shape=(), dtype=int32, numpy=6>

## eager execution

In [27]:
def op(a,b):
    c = a*b+1
    d = a*b*3
    print(c)
    print(d)

In [28]:
op(a,b)

tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)


## lazy execution

In [29]:
@tf.function
def op(a,b):
    c = a*b+1
    d = a*b*3
    print(c)
    print(d)

In [30]:
op(a,b)

Tensor("add:0", shape=(), dtype=int32)
Tensor("mul_2:0", shape=(), dtype=int32)
