In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('marks.csv')

In [3]:
data

name  duration  marks
0  abhi         4     40
1  eric         6     60
2  jack         2     20
3  amit         6     60

In [4]:
type(data)

pandas.core.frame.DataFrame

In [6]:
data['name']

0    abhi
1    eric
2    jack
3    amit
Name: name, dtype: object

In [10]:
x = data['duration']

In [11]:
y = data['marks']

In [9]:
data.iloc[2]

name        jack
duration       2
marks         20
Name: 2, dtype: object

In [13]:
x.values

array([4, 6, 2, 6])

In [15]:
X = x.values.reshape((4,1))

In [16]:
X

array([[4],
       [6],
       [2],
       [6]])

In [18]:
X.shape

(4, 1)

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
mind = LinearRegression()

In [23]:
mind.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
data.describe()

duration      marks
count  4.000000   4.000000
mean   4.500000  45.000000
std    1.914854  19.148542
min    2.000000  20.000000
25%    3.500000  35.000000
50%    5.000000  50.000000
75%    6.000000  60.000000
max    6.000000  60.000000

In [27]:
data.shape

(4, 3)

In [28]:
mind.coef_

array([10.])

In [29]:
mind.predict([[9]])

array([90.])