In [ ]:
l=[1,2,3,4]

In [2]:
type(l)

list

In [3]:
import numpy as np

In [4]:
a = np.array(l)

In [5]:
a

array([1, 2, 3, 4])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
name = ['a','b','c','d','e']

In [9]:
a1 = np.array('name')

In [10]:
a1

array('name', dtype='<U4')

In [11]:
type(a1)

numpy.ndarray

In [12]:
a1.dtype

dtype('<U4')

In [13]:
a1.shape

()

In [14]:
x=[1,2,3,4,5,6,7,8,9]

In [15]:
a2=np.array(x)

In [16]:
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a2.shape

(9,)

In [18]:
a3=a2.reshape(3,3)

In [19]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a3.shape

(3, 3)

In [21]:
b=np.zeros( (5,5) )

In [22]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
b + 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [24]:
c = np.zeros((5,5)) + 20

In [25]:
c

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [26]:
c * 10

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

In [27]:
d = np.zeros((6,6)) + 10

In [28]:
d

array([[10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.]])