In [1]:
l = [1,2,3,4,5]

In [2]:
type(l)

list

In [3]:
len(l)

5

In [4]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('int64')

In [9]:
name = ['a','b','c','d','e']

In [10]:
b = np.array('name')

In [11]:
b

array('name', dtype='<U4')

In [13]:
type(b)

numpy.ndarray

In [15]:
b.dtype

dtype('<U4')

In [16]:
x=[1,2,3,4,5,6,7,8,9]

In [17]:
c = np.array(x)

In [20]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c_reshape = c.reshape(3,3)

In [23]:
c_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
c_reshape.shape

(3, 3)